- vint/asset/default_config.yaml
Now, the policy `ProhibitUnusedVariable` have many false-positives of `autocmd` and `map` family.
So, we should disable temporary ProhibitUnusedVariable (until #104 are fixed).
> Disable ProhibitUnusedVariable

- test/asserting/policy.py
- test/fixture/policy/prohibit_implicit_scope_variable_invalid.vim
- test/fixture/policy/prohibit_implicit_scope_variable_valid.vim
- test/integration/vint/linting/policy/test_prohibit_implicit_scope_variable.py
- test/unit/vint/linting/policy/test_abstract_policy.py
- vint/asset/default_config.yaml
- vint/ast/plugin/scope_plugin/__init__.py
- vint/linting/linter.py
- vint/linting/policy/abstract_policy.py
- vint/linting/policy/prohibit_implicit_scope_variable.py
Autoload functions always have the global scope visibility and are
easily distinguishable so let them omit an explicit scope.
Also update the ProhibitImplicitScopeVariable policy reference string
since it also applies to functions.
> Allow autoload functions omit an explicit scope

- vint/linting/cli.py
- vint/linting/config/config_cmdargs_source.py
- vint/linting/formatter/formatter.py
Related: #131 
- `file_path`
- `file_name`
- `line_number`
- `column_number`
- `severity`
- `description`
- `policy_name`
- `reference`
```shell
vint --format '{file_path}:{line_number}:{column_number}: {severity}: {description} (see {reference})'
```
> Support --format option

- requirements.txt
- setup.py
> Remove enum34 from requirements.txt and add it in setup.py dynamically

- requirements.txt
- setup.py
pathlib is a part of Python since 3.4.
See https://www.python.org/dev/peps/pep-0428/
> Only require pathlib with Python < 3.4

- test/fixture/policy/prohibit_implicit_scope_variable_invalid.vim
- test/fixture/policy/prohibit_implicit_scope_variable_valid.vim
- test/integration/vint/linting/policy/test_prohibit_implicit_scope_variable.py
- vint/ast/plugin/scope_plugin/__init__.py
- vint/linting/policy/prohibit_implicit_scope_variable.py
関数名にもスコープを明示しろという警告が出てしまう問題を修正しました．
```vim
function SomeFunc()
endfunction
function aaa#bbb()
endfunction
```
実行結果：
```
foo.vim:1:10: Make the scope explicit like `g:SomeFunc` (see Anti-pattern of vimrc (Scope of identifier))
foo.vim:4:10: Make the scope explicit like `g:aaa#bbb` (see Anti-pattern of vimrc (Scope of identifier))
```
Vim script 的には関数名に `g:` をつけるとエラーになる（昔は通ってしまっていた）はずです．
まだテストが追加できていないのでマージできる状態ではないです．
修正が正しいかどうか（Python よく知らないので変な修正になってるかも…）をレビューお願いします．問題無さそうならテスト足してみます．
直りそうな issue: #135
> Fix invalid 'implicit scope' report on global or autoload function

- vint/linting/policy/prohibit_abbreviation_option.py
- vint/linting/policy/prohibit_autocmd_with_no_group.py
- vint/linting/policy/prohibit_command_with_unintended_side_effect.py
- vint/linting/policy/prohibit_encoding_opt_after_scriptencoding.py
- vint/linting/policy/prohibit_no_abort_function.py
- vint/linting/policy/prohibit_set_nocompatible.py
I fixed a few grammatical errors in the output messages (and a couple in the doc strings) while trying to keep the meaning as close to the original intent as possible.
> Edit some of the output messages for grammar

- vint/asset/default_config.yaml
- vint/linting/policy_set.py
> Suppress ProhibitImplicitScopeVariable when --error specified

- setup.py
Without an asterisk only the topmost 'test' module is not installed.
> Properly exclude all modules under test/ directory

- test/integration/vint/linting/policy/test_prohibit_implicit_scope_variable.py
- vint/asset/default_config.yaml
- vint/linting/policy/prohibit_implicit_scope_variable.py
Initially introduced in PR#129, suppress_autoload option became obsolete
after PR#136 was merged as vint now skips scope checks for all functions
regardless of suppress_autoload option's value.
Code that handles policy options, which was also added in PR#129, is
preserved for a possible future reuse.
(It's fine, this code is covered with tests.)
Fixes issue #152.
> ProhibitImplicitScopeVariable: remove obsolete suppress_autoload option

- vint/linting/config/config_project_source.py
Fixes https://github.com/Kuniwak/vint/issues/194.
Maybe the `break` was meant to really break already, and the outer loop was an oversight?!
> ConfigProjectSource: return first found config

- README.rst
Link to Google Vimscript Style Guide seems to be broken (gives 404). This change updates the link
> Update link to Google Vimscript Style Guide

- vint/linting/policy/prohibit_missing_scriptencoding.py
`chardet.detect(b'')` returns `{'encoding': None, 'confidence': 0.0}`,
which made `_check_script_has_multibyte_char` return True for an empty
file.
> ProhibitMissingScriptEncoding: handle empty file

- test/integration/vint/linting/policy/test_prohibit_implicit_scope_builtin_variable.py
- vint/linting/policy/prohibit_implicit_scope_builtin_variable.py
The name of the policy rule "ProhibitImplicitScopeBuiltinVariable" is
actually implemented as "ProhibitImplicitScopeBuitlinVariable" ("t" and
"l" in Builtin are swapped).
> Fix typo in policy rule name

- requirements.txt
Arch Linux has chardet 3.0.3 by now, and that causes Vint to break.
> Bump chardet requirement

- requirements.txt
- setup.py
> Install typing when Python is older than 3.6

- test/acceptance/test_cli.py
- test/acceptance/test_cli_vital.py
If test command is just 'vint' and you already have vint installed, then
the test suite calls an installed binary in majority of cases since cwd
usually goes last or missing from PATH. Use 'bin/vint' in tests instead.
Fixes issue #223.
> tests: use 'bin/vint' in tests to avoid calling an installed vint copy

- test-requirements.txt
- test/asserting/policy.py
- test/fixture/ast/scope_plugin/fixture_to_scope_plugin_nested_map_and_filter.vim
- test/fixture/policy/prohibit_unnecessary_double_quote_invalid.vim
- test/fixture/policy/prohibit_unnecessary_double_quote_valid.vim
- test/unit/vint/ast/plugin/scope_plugin/test_map_and_filter_parser.py
- vint/ast/parsing.py
- vint/ast/plugin/scope_plugin/map_and_filter_parser.py
- vint/linting/policy/prohibit_unnecessary_double_quote.py
Before this patch, `ProhibitUnnecessaryDoubleQuote` report warnings caused by the code:
```viml
map([0, 1, 2], ' "x" ')
"                ^^^
"                Prefer single quoted strings (see Google VimScript Style Guide (Strings))
```
After this patch, Vint will suppress the warnings:
```viml
map([0, 1, 2], ' "x" ')
" (no warnings)
```
This feature can be an option of `ProhibitUnnecessaryDoubleQuote`.
But I feel this option is useless. Because the following code is noisy:
```
map([0, 1, 2], ' ''x'' ')
```
> Suppress warnings caused by map([], ' "x" ')

- README.rst
> " vint: -ProhibitAbbreviationOption
>
> let s:save_cpo = &cpo set cpo&vim
>
> " vint: +ProhibitAbbreviationOption
>
> " do something...
>
> " vint: -ProhibitAbbreviationOption
>
> let &cpo = s:save_cpo unlet s:save_cpo
コメントでポリシーを enable/disable するサンプルがこんな感じ↑に崩壊してしまっていたので直しました
> Fix a broken code block for example

- .coveragerc
- .travis.yml
- CONTRIBUTING.rst
- MANIFEST.in
- codecov.yml
- requirements.txt
- setup.cfg
- setup.py
- test-requirements.txt
- tox.ini
Fixes https://github.com/Kuniwak/vint/issues/287
Please review carefully.
Based on pytest's setup.py, which supports different marker levels, but I hope we do not need that: https://github.com/pytest-dev/pytest/blob/master/setup.py.
> setup.py: fix requirements

- vint/linting/policy/prohibit_no_abort_function.py
The ProhibitNoAbortFunction checks for both the abort attribute and
whether the bang is used for the function command, but the error didn't
mention this.
This is quite confusing, and it took me a while to figure out why vint
was failing on two functions in my project. This should clarify it.
Fixes #232
> Clarify the ProhibitNoAbortFunction message

- .coveragerc
- .travis.yml
- test/acceptance/test_cli_vital.py
- tox.ini
It was not working after fadce51 at all, but did not report the failure
correctly.
It fails currently ("Undefined variable: s:next" etc),
https://github.com/Kuniwak/vint/issues/274 - but gets skipped without
the submodule being checked out.
> tests: revisit/fix test_cli_vital

- .pre-commit-hooks.yaml
This allows repos using pre-commit (https://pre-commit.com) to run vint
before committing any changes and to keep repos consistent.
You can see an example of usage in my vim settings repo:
https://github.com/ViViDboarder/vim-settings
The `.pre-commit-config.yaml` file contains the actual configuration. In
addition, I've got some handy targets in my `Makefile` to ease the
installation of the hooks.
> Add support for using as a pre-commit hook

- vint/ast/plugin/scope_plugin/scope_linker.py
> SyntaxWarning: "is not" with a literal. Did you mean "!="?
> Fix SyntaxWarning with py38

- vint/ast/plugin/scope_plugin/__init__.py
- vint/compat/itertools/__init__.py
- vint/compat/unittest/__init__.py
- vint/linting/cli.py
- vint/linting/env.py
- vint/linting/policy_set.py
Not importing `pkg_resources` should be beneficial with regard to
startup performance.
> qa: fix F401 (unused import)

- vint/linting/policy/prohibit_unnecessary_double_quote.py
One line to allow double quotes if there is a dollar in the string.
As example from my vimrc: 
```vim
let $h = expand($HOME)
let $w = expand("$h/wiki/wiki") | let $wiki = $w
```
Cleaner than `$h . '/wiki/wiki'` in my opignon
> Policy: double quote: allow if dollar in string

- .travis.yml
- setup.py
It fails to install PyYAML on Travis:
> Collecting PyYAML>=3.11 (from vim-vint==0.3.21.dev53+g930a103)
>   Downloading https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz (268kB)
> ERROR: PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
> Drop support for Python 3.4

- README.rst
Today i installed Vimjas/vint with vim-plug and used it with ALE (https://github.com/dense-analysis/ale/#readme) I only needed to add the this ling to the plugin manager.
> Update README.rst: add vim-plug
