test/unit/vint/ast/test_parsing.py
vint/ast/parsing.py

Care empty file

---

dev_tool/qa
test/fixture/ast/scope_plugin/fixture_to_scope_plugin_declaring_with_dict_key.vim
test/fixture/policy/prohibit_implicit_scope_variable_invalid.vim
test/fixture/policy/prohibit_implicit_scope_variable_valid.vim
test/fixture/policy/prohibit_unused_variable_valid.vim
test/integration/vint/linting/policy/test_prohibit_implicit_scope_variable.py
test/unit/vint/ast/plugin/scope_plugin/test_identifier_classifier.py
test/unit/vint/ast/plugin/scope_plugin/test_scope_detector.py
vint/ast/plugin/scope_plugin/__init__.py
vint/ast/plugin/scope_plugin/identifier_classifier.py
vint/ast/plugin/scope_plugin/scope_detector.py
vint/ast/plugin/scope_plugin/scope_linker.py
vint/linting/linter.py
vint/linting/policy/prohibit_implicit_scope_variable.py

Warn variables have an implicit scope visibility

---

test/fixture/ast/scope_plugin/fixture_to_scope_plugin_calling_func.vim
test/unit/vint/ast/plugin/scope_plugin/test_identifier_classifier.py
vint/ast/plugin/scope_plugin/identifier_classifier.py

Care delfunction

---

extlib/vimlparser.py

Care line-continuation

---

test/fixture/policy/prohibit_implicit_scope_builtin_variable_invalid.vim
test/fixture/policy/prohibit_implicit_scope_builtin_variable_valid.vim
test/fixture/policy/prohibit_implicit_scope_variable_valid.vim
test/integration/vint/linting/policy/test_prohibit_implicit_scope_builtin_variable.py
test/integration/vint/linting/policy/test_prohibit_implicit_scope_variable.py
vint/linting/policy/prohibit_implicit_scope_builtin_variable.py
vint/linting/policy/prohibit_implicit_scope_variable.py

Prohibit implicit builtin

---

test/fixture/policy/prohibit_implicit_scope_builtin_variable_valid.vim
vint/ast/dictionary/builtins.py
vint/ast/plugin/scope_plugin/scope_detector.py

Care variables can have only explicit scope

---

.travis.yml

http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Try to make travis.ci faster

---

vint/linting/config/config_cmdargs_source.py

fixed a bug where enable neovim would always be set to true

---

README.rst

https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/vim/vint.vim

Highlight Syntastic's built in vint checker

---

vint/linting/cli.py
vint/linting/config/config_cmdargs_source.py

Support --no-color option

---

requirements.txt

Fixes https://github.com/Kuniwak/vint/issues/162#issuecomment-243236874

requirements.txt: Use compatability operator

---

setup.py

Require enum34 >= 1.0.4

---

vint/ast/node_type.py
vint/ast/traversing.py

Just recognize lambda, but do nothing.
This should fix #227.

Initial support for lambda

---

requirements.txt
test/fixture/ast/inline_python.vim
test/fixture/config/xdg_config_home/.vintrc.yaml
test/unit/vint/linting/config/test_config_global_source.py
test/unit/vint/linting/test_env.py
test/unit/vint/utils/test_array.py
vint/linting/config/config_filenames.py
vint/linting/config/config_global_source.py
vint/linting/env.py
vint/utils/array.py

Support XDG_CONFIG_HOME

---

README.rst

Vint was added to the official Fedora Package Collection
https://src.fedoraproject.org/rpms/vint

Remove Fedora Copr build status

---

.travis.yml
CONTRIBUTING.rst
setup.py
tox.ini

If still you want pypy support, please help us.

Drop pypy support

---

vint/ast/parsing.py

Remove unnecessary code

---

test/fixture/ast/scope_plugin/fixture_to_scope_plugin_issue_256.vim
test/fixture/policy/prohibit_invalid_map_call_invalid.vim
test/fixture/policy/prohibit_invalid_map_call_valid.vim
test/integration/vint/linting/policy/test_prohibit_invalid_map_call.py
test/unit/vint/ast/plugin/scope_plugin/test_map_and_filter_parser.py
vint/ast/plugin/scope_plugin/map_and_filter_parser.py
vint/linting/policy/prohibit_invalid_map_call.py

Fix a bug caused by less args for map function

---

vint/asset/default_config.yaml

Fixes: https://github.com/Kuniwak/vint/issues/245

Disable ProhibitImplicitScopeVariable by default

---

vint/linting/config/config_file_source.py

Ref: https://github.com/Kuniwak/vint/issues/279#issuecomment-458106093

Use yaml.safe_load

---

setup.py

Closes https://github.com/Kuniwak/vint/pull/282.

setup.py: add long_description

---

test/fixture/policy/prohibit_equal_tilde_operator_invalid.vim
test/fixture/policy/prohibit_equal_tilde_operator_valid.vim
test/integration/vint/linting/policy/test_prohibit_equal_tilde_operator.py
vint/linting/policy/prohibit_equal_tilde_operator.py

Fixes https://github.com/Kuniwak/vint/issues/195.

ProhibitEqualTildeOperator: only consider alpha chars

---

MANIFEST.in
setup.cfg

Closes https://github.com/Kuniwak/vint/issues/300

Add tests to sdist

---

.travis.yml

This is in preparation of adding a separate checkqa tox env.

ci: report all coverage jobs to coveralls

---

vint/linting/policy/prohibit_unnecessary_double_quote.py

Revert "Policy: double quote: allow if dollar in string"

---

.travis.yml
setup.py

Reverts 1937372, continuation of https://github.com/Kuniwak/vint/pull/346.

Keep support for Python 3.4 - pin PyYAML properly

---

.travis.yml

Fixes https://github.com/Vimjas/vint/issues/315.

ci: Travis: add deploy stage

---

README.rst

I fixed README's url.
Could you check this changing?

[fix] document's url
